### ISSUE TITLE
After signing in with Google, get returned to broken URL 

### ISSUE THREAD

**Issue by LaurieJ** [Scifabric/crowdcrafting.org#18] opened 2013-02-04 11:32 UTC
For first time signing in - from "community" page, click to sign in; select "sign in with google", sign in, agree to use of Google profile data, then get redirected to http://crowdcrafting.org/%252Fapp%252Fnew which is "page not found" - would be nice to end up on a friendly page :)

Same issue when signing in using google subsequently (ie not first time)

![Screen Shot 2013-02-04 at 11 27 41](https://f.cloud.github.com/assets/457927/123389/7474392c-6ebe-11e2-8d2c-ff89336e0a9e.png)

**Comment by teleyinex** [comment] 2013-02-07 11:19
Hi,

I've revoked all my accounts in Google just to check this issue and followed your steps and I cannot reproduce the issue, can you help me to triage this issue? For me it works perfectly well in all the redirections and even when sign in the first time and afterwards. Would you mind to give me more feedback and a step by step guide that you did for getting that error?

Thanks in advance!

**Comment by LaurieJ** [comment] 2013-02-07 11:26
Go to crowdcrafting.org (Chrome on OSX but I doubt that matters), click "community" in top bar, click "sign in", select "google", select one of my two Google accounts (it's a standard google account), get error page. I've just repeated it twice. cf http://screencast.com/t/THSGRAjRCp

**Comment by teleyinex** [comment] 2013-02-07 11:32
Ok, I do not have the step in Google to choose another account, so I cannot test that: can you paste here the URL that Google creates when you get your two accounts choice screen? I want to look at that URL

Thanks!

**Comment by LaurieJ** [comment] 2013-02-07 11:34
https://accounts.google.com/AccountChooser?service=lso&continue=https%3A%2F%2Faccounts.google.com%2Fo%2Foauth2%2Fauth%3Fresponse_type%3Dcode%26scope%3Dhttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile%2Bhttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%26redirect_uri%3Dhttp%3A%2F%2Fcrowdcrafting.org%2Fgoogle%2Foauth_authorized%26state%3Daitnuqip%26client_id%3D31745951813.apps.googleusercontent.com%26hl%3Den%26from_login%3D1%26as%3D61bb9a1ce129b96c&btmpl=authsub&hl=en

**Comment by teleyinex** [comment] 2013-02-07 11:47
Thanks! Apparently the URL that Google uses the "state" parameter that PyBossa uses for doing the redirection, so it is creating a non-sanitize URL. Now I know where the "problem is", so I'll think about a solution. THANKS A LOT!!!

**Comment by teleyinex** [comment] 2013-02-07 11:56
Closing this issue here, please check the proper issue in the PyBossa [repo](https://github.com/PyBossa/pybossa/issues/361)

**Closed as completed by teleyinex** 2013-02-07 11:56 UTC

**Comment by teleyinex** [comment] 2013-02-07 12:20
Fix has been deployed. Can you try again?

**Comment by LaurieJ** [comment] 2013-02-07 12:22
fixed :)

**Comment by teleyinex** [comment] 2013-02-07 12:22
I'm relieved :+1: sorry for all the trouble!
